# Generated by Django 3.0.3 on 2020-03-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesessions',
            name='access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicesessions',
            name='refresh_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicesessions',
            name='token_born',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
