# Generated by Django 3.0.4 on 2020-03-28 16:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_auto_20200319_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDataBase',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersSessions',
            fields=[
                ('session_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_uuid', models.UUIDField()),
                ('access_token', models.CharField(max_length=100, null=True)),
                ('refresh_token', models.CharField(max_length=100, null=True)),
                ('token_born', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
