# Generated by Django 3.0.3 on 2020-02-28 08:25

import dancers_database.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DancersDataBase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1, validators=[dancers_database.validators.genderValid])),
                ('club', models.CharField(max_length=50)),
                ('points_in_E_class', models.SmallIntegerField()),
                ('points_in_D_class', models.SmallIntegerField()),
                ('points_in_C_class', models.SmallIntegerField()),
                ('points_in_B_class', models.SmallIntegerField()),
                ('points_in_A_class', models.SmallIntegerField()),
                ('points_in_S_class', models.SmallIntegerField()),
                ('points_in_M_class', models.SmallIntegerField()),
                ('trainer_rank', models.CharField(max_length=50, validators=[dancers_database.validators.trainerValid])),
                ('referee_rank', models.CharField(max_length=50, validators=[dancers_database.validators.refereeValid])),
                ('sport_rank', models.CharField(max_length=50, validators=[dancers_database.validators.sportValid])),
                ('class_rank', models.CharField(max_length=3, validators=[dancers_database.validators.classValid])),
            ],
        ),
    ]
